#ifndef MASTER_COMMUNICATION_H
#define	MASTER_COMMUNICATION_H

typedef enum{
    SLAVE_MODE_VOLTAGE = 0,
    SLAVE_MODE_CURRENT = 1,
    SLAVE_MODE_FREE = 2
}SLAVE_MODE;

#endif	/* MASTER_COMMUNICATION_H */
